const root = document.querySelector("#portal");
const token = location.hash.slice(1);
history.replaceState(null, "", "/portal.html");
const escapeHtml = (value = "") => String(value).replace(/[&<>'"]/g, (char) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", "'": "&#39;", '"': "&quot;" }[char]));
const money = (minor = 0, currency = "ZAR") => new Intl.NumberFormat("en-ZA", { style: "currency", currency }).format((Number(minor) || 0) / 100);
const date = (value) => value ? new Intl.DateTimeFormat("en-ZA", { dateStyle: "medium" }).format(new Date(`${String(value).slice(0,10)}T12:00:00`)) : "—";
const request = async (path, options = {}) => { const response = await fetch(path, { ...options, headers: { "X-Forma-Portal-Token": token, ...(options.headers || {}) } }); const payload = response.headers.get("content-type")?.includes("json") ? await response.json() : null; if (!response.ok) throw new Error(payload?.error?.message || "This secure link is invalid or expired."); return payload?.data ?? payload; };

function render(portal) {
  const record = portal.document; const data = record.data || {}; const totals = record.totals || {}; const customer = data.customer || {}; const supplier = data.supplier || {}; const currency = data.currency || "ZAR"; const balance = Number(record.balance_due_minor ?? totals.total_minor) || 0;
  const lines = (totals.lines?.length ? totals.lines : data.items || []).map((item) => `<div class="line"><span><strong>${escapeHtml(item.description || "Item")}</strong></span><span>${Number(item.quantity) || 0}</span><span>${money(item.unit_price_minor, currency)}</span><span>${money(item.total_minor ?? (Number(item.quantity) || 0) * (Number(item.unit_price_minor) || 0), currency)}</span></div>`).join("");
  const payment = portal.payment_links?.[0]; const canRespond = record.document_type === "quote" && record.status === "sent";
  root.innerHTML = `<div class="portal-shell"><section class="portal-card document-card"><div class="document-head"><div><span>${escapeHtml(record.document_type)}</span><h1>${escapeHtml(data.document_title || record.document_type)}</h1><p>${escapeHtml(record.number)}</p></div><div><span>Status</span><strong class="status">${escapeHtml(record.status)}</strong></div></div><div class="document-meta"><div><small>From</small><strong>${escapeHtml(supplier.name || "Business")}\n${escapeHtml(supplier.address || "")}</strong></div><div><small>Issued</small><strong>${date(data.issue_date)}</strong></div><div><small>${record.document_type === "quote" ? "Expires" : "Due"}</small><strong>${date(data.expiry_date || data.due_date)}</strong></div><div><small>${record.document_type === "receipt" ? "Received from" : "Prepared for"}</small><strong>${escapeHtml(customer.name || "Customer")}</strong></div></div><div class="line-table"><div class="line head"><span>Description</span><span>Qty</span><span>Rate</span><span>Total</span></div>${lines}</div><div class="totals"><div class="total-row"><span>Subtotal</span><strong>${money(totals.subtotal_minor, currency)}</strong></div>${totals.discount_minor ? `<div class="total-row"><span>Discount</span><strong>-${money(totals.discount_minor, currency)}</strong></div>` : ""}<div class="total-row"><span>Tax</span><strong>${money(totals.tax_minor, currency)}</strong></div><div class="total-row grand"><span>Total</span><strong>${money(totals.total_minor, currency)}</strong></div></div></section><aside class="portal-card portal-side"><h2>${escapeHtml(customer.name || "Your document")}</h2><p>Review the document, download a copy, and use any available action below.</p>${record.document_type === "invoice" ? `<div class="amount-due"><small>Balance due</small><strong>${money(balance, currency)}</strong></div>` : ""}${payment ? `<a class="button primary" href="${escapeHtml(payment.checkout_url)}" target="_blank" rel="noopener">Pay with ${escapeHtml(payment.provider)}</a>` : ""}<button class="button" id="downloadPdf">Download PDF</button>${canRespond ? `<div class="action-grid"><button class="button primary" data-quote-action="accepted">Accept</button><button class="button danger" data-quote-action="declined">Decline</button></div>` : ""}<p class="portal-note">This link expires ${date(portal.link.expires_at)}. Payment status is recorded only after provider confirmation.</p></aside></div>`;
  document.querySelector("#downloadPdf").onclick = downloadPdf;
  document.querySelectorAll("[data-quote-action]").forEach((button) => button.onclick = () => quoteAction(button.dataset.quoteAction));
}
async function downloadPdf() { try { const response = await fetch("/api/public/portal/pdf", { headers: { "X-Forma-Portal-Token": token } }); if (!response.ok) throw new Error("PDF could not be downloaded"); const url = URL.createObjectURL(await response.blob()); const link = document.createElement("a"); link.href = url; link.download = "forma-document.pdf"; link.click(); setTimeout(() => URL.revokeObjectURL(url), 30000); } catch (error) { alert(error.message); } }
async function quoteAction(action) { if (!confirm(`${action === "accepted" ? "Accept" : "Decline"} this quote?`)) return; try { await request(`/api/public/portal/quote/${action}`, { method: "POST" }); const portal = await request("/api/public/portal"); render(portal); } catch (error) { alert(error.message); } }

if (!token) root.innerHTML = `<section class="portal-error"><h1>Secure link required</h1><p>Open the complete link shared by the sender.</p></section>`;
else request("/api/public/portal").then(render).catch((error) => { root.innerHTML = `<section class="portal-error"><h1>Document unavailable</h1><p>${escapeHtml(error.message)}</p></section>`; });
