import { randomUUID } from "node:crypto";
import { calculateTotals, readiness, withoutPristineTrailingItems } from "./db.js";
import { DEFAULT_EMAIL_TEMPLATES, PURPOSES, renderTemplate, validateTemplate } from "./email.js";
import { templateFor } from "./templates.js";

const now = () => new Date().toISOString();
const today = () => now().slice(0, 10);
const TYPES = ["invoice", "quote", "receipt"];
const STATUS = { quote: ["draft", "sent", "accepted", "declined", "expired", "converted"], invoice: ["draft", "finalized", "sent", "partially_paid", "paid", "overdue", "void", "refunded"], receipt: ["draft", "issued", "void"] };
const DEFAULT_PROFILE = { name: "Forma Studio", email: "billing@forma.co.za", address: "", vat_registered: false, vat_number: "", default_currency: "ZAR", default_terms_days: 30 };
const DEFAULT_PREFIXES = { invoice: "INV", quote: "QUO", receipt: "REC" };
const DEFAULT_REMINDER_RULES = [
  { id: "before_due_7", label: "7 days before due", offset_days: -7, purpose: "invoice_reminder", active: true },
  { id: "due_today", label: "On due date", offset_days: 0, purpose: "invoice_reminder", active: true },
  { id: "overdue_7", label: "7 days overdue", offset_days: 7, purpose: "invoice_overdue", active: true }
];

function domainError(message, status = 422, code = "VALIDATION_ERROR", details) { return Object.assign(new Error(message), { status, code, details }); }
function assertType(type) { if (!TYPES.includes(type)) throw domainError("document_type must be invoice, quote, or receipt"); }
function assertStatus(type, status) { if (!STATUS[type]?.includes(status)) throw domainError(`Invalid ${type} status '${status}'`); }
function dateOnly(value, field) { const input = String(value || ""); if (!/^\d{4}-\d{2}-\d{2}$/.test(input) || Number.isNaN(new Date(`${input}T12:00:00Z`).getTime())) throw domainError(`${field} must be a valid YYYY-MM-DD date`); return input; }
function addDays(value, days) { const date = new Date(`${dateOnly(value, "date")}T12:00:00Z`); date.setUTCDate(date.getUTCDate() + days); return date.toISOString().slice(0, 10); }
function addMonths(value, months) { const [year, month, day] = dateOnly(value, "date").split("-").map(Number); const last = new Date(Date.UTC(year, month + months, 0)).getUTCDate(); return new Date(Date.UTC(year, month - 1 + months, Math.min(day, last), 12)).toISOString().slice(0, 10); }
function nextRecurringDate(value, frequency) { if (frequency === "weekly") return addDays(value, 7); if (frequency === "monthly") return addMonths(value, 1); if (frequency === "quarterly") return addMonths(value, 3); if (frequency === "yearly") return addMonths(value, 12); throw domainError("frequency must be weekly, monthly, quarterly, or yearly"); }
function asMinor(value, field, { allowZero = true } = {}) { const amount = Number(value); if (!Number.isFinite(amount) || amount < 0 || (!allowZero && amount === 0)) throw domainError(`${field} must be a ${allowZero ? "non-negative" : "positive"} integer minor-unit amount`); return Math.round(amount); }
function maskDetails(details = {}) { const result = { ...details }; for (const field of ["account_number", "account", "iban", "routing_number"]) if (result[field]) { const value = String(result[field]); result[field] = `${"*".repeat(Math.max(0, value.length - 4))}${value.slice(-4)}`; } return result; }
const validAddress = (address) => /^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(address);
const safeHtml = (value) => String(value || "").replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;").replace(/"/g, "&quot;").replace(/'/g, "&#39;");

function mapDocument(row) {
  if (!row) return null;
  const data = row.data_json || {}; const totals = row.totals_json || {}; const snapshot = row.snapshot_json || null;
  return { id: row.id, document_type: row.document_type, number: row.number, status: row.status, customer_id: row.customer_id, source_document_id: row.source_document_id, recurring_schedule_id: row.recurring_schedule_id || null, data, totals, snapshot, amount_paid_minor: row.amount_paid_minor, balance_due_minor: row.balance_due_minor, created_at: row.created_at, updated_at: row.updated_at, issued_at: row.issued_at, finalized_at: row.finalized_at, readiness: readiness(data, totals, row.document_type) };
}
function mapPaymentMethod(row, sensitive = false) { return row && { ...row, active: Boolean(row.active), is_default: Boolean(row.is_default), details: sensitive ? row.details_json || {} : maskDetails(row.details_json || {}), details_json: undefined, workspace_id: undefined }; }
function mapEmailAttempt(row, idempotent = false) { return row && { ...row, recipients: row.recipients_json || [], rendered: row.rendered_json || {}, recipients_json: undefined, rendered_json: undefined, workspace_id: undefined, idempotent }; }
function mapReminderRule(row) { return row && { id: row.id, label: row.label, offset_days: row.offset_days, purpose: row.purpose, active: Boolean(row.active), created_at: row.created_at, updated_at: row.updated_at }; }
function mapReminderDelivery(row) { return row && { id: row.id, document_id: row.document_id, rule_id: row.rule_id, due_date: row.due_date, scheduled_for: row.scheduled_for, attempt_id: row.attempt_id || null, status: row.status, provider_error: row.provider_error || null, created_at: row.created_at, updated_at: row.updated_at }; }

export class SupabaseStore {
  constructor({ getAuth }) { this.getAuth = getAuth; this.seeded = new Map(); }
  close() {}
  context() { const auth = this.getAuth?.(); if (!auth?.workspaceId || !auth.supabaseFetch) throw domainError("A selected authenticated workspace is required", 409, "WORKSPACE_REQUIRED"); return { auth, workspaceId: auth.workspaceId }; }
  requireRole(required = "member") { const rank = { viewer: 10, member: 20, admin: 30, owner: 40 }; const role = this.context().auth.role; if ((rank[role] || 0) < rank[required]) throw domainError(`${required[0].toUpperCase()}${required.slice(1)} workspace access is required`, 403, "WORKSPACE_ACCESS_DENIED"); }
  async request(path, { useService = false, ...options } = {}) {
    const { auth } = this.context(); const fetcher = useService ? auth.serviceFetch : auth.supabaseFetch; if (!fetcher) throw domainError("The server-only Supabase mutation key is not configured", 503, "TENANT_STORE_NOT_CONFIGURED"); const response = await fetcher(path, options); const payload = await response.json().catch(() => null);
    if (!response.ok) {
      const code = payload?.code; const status = code === "P0002" ? 404 : ["23505", "23514", "40001"].includes(code) ? 409 : code === "42501" ? 403 : response.status;
      const publicCode = status === 404 ? "NOT_FOUND" : status === 409 ? "CONFLICT" : status === 403 ? "WORKSPACE_ACCESS_DENIED" : "SUPABASE_DATA_ERROR";
      throw domainError(payload?.message || "Supabase data request failed", status, publicCode, payload?.details);
    }
    return payload;
  }
  async select(table, query = "", { single = false, useService = false } = {}) { const join = query ? `&${query}` : ""; const rows = await this.request(`/rest/v1/${table}?select=*&workspace_id=eq.${this.context().workspaceId}${join}`, { useService }); return single ? rows?.[0] || null : rows || []; }
  async insert(table, body, { onConflict = "", upsert = false, single = true } = {}) {
    this.requireRole();
    const payload = (Array.isArray(body) ? body : [body]).map((row) => ({ ...row, workspace_id: this.context().workspaceId }));
    const query = onConflict ? `?on_conflict=${encodeURIComponent(onConflict)}` : "";
    const resolution = upsert ? `resolution=${upsert === "ignore" ? "ignore-duplicates" : "merge-duplicates"},` : "";
    const rows = await this.request(`/rest/v1/${table}${query}`, { useService: true, method: "POST", headers: { Prefer: `${resolution}return=representation` }, body: JSON.stringify(Array.isArray(body) ? payload : payload[0]) });
    return single ? rows?.[0] || null : rows || [];
  }
  async update(table, idQuery, body, { single = true } = {}) { this.requireRole(); const rows = await this.request(`/rest/v1/${table}?workspace_id=eq.${this.context().workspaceId}&${idQuery}`, { useService: true, method: "PATCH", headers: { Prefer: "return=representation" }, body: JSON.stringify(body) }); return single ? rows?.[0] || null : rows || []; }
  async remove(table, idQuery, { single = true } = {}) { this.requireRole(); const rows = await this.request(`/rest/v1/${table}?workspace_id=eq.${this.context().workspaceId}&${idQuery}`, { useService: true, method: "DELETE", headers: { Prefer: "return=representation" } }); return single ? rows?.[0] || null : rows || []; }
  async rpc(name, body) { this.requireRole(); return this.request(`/rest/v1/rpc/${name}`, { useService: true, method: "POST", headers: { Prefer: "return=representation" }, body: JSON.stringify(body) }); }
  storageKey(key) { const normalized = String(key || "").replace(/^\/+/, ""); const prefix = `${this.context().workspaceId}/`; if (!normalized.startsWith(prefix) || normalized.includes("..")) throw domainError("Storage path is outside the active workspace", 403, "WORKSPACE_ACCESS_DENIED"); return normalized.split("/").map(encodeURIComponent).join("/"); }
  async uploadObject(key, content, contentType) { this.requireRole(); const response = await this.context().auth.supabaseFetch(`/storage/v1/object/forma-private/${this.storageKey(key)}`, { method: "POST", headers: { "Content-Type": contentType, "x-upsert": "false" }, body: content }); if (!response.ok) { const payload = await response.json().catch(() => ({})); throw domainError(payload.message || "Object upload failed", response.status, "STORAGE_UPLOAD_FAILED"); } return key; }
  async downloadObject(key) { const response = await this.context().auth.supabaseFetch(`/storage/v1/object/authenticated/forma-private/${this.storageKey(key)}`, { headers: { Accept: "application/octet-stream" } }); if (!response.ok) return null; return Buffer.from(await response.arrayBuffer()); }
  async deleteObject(key) { this.requireRole(); const response = await this.context().auth.supabaseFetch(`/storage/v1/object/forma-private/${this.storageKey(key)}`, { method: "DELETE" }); return response.ok; }

  async ensureSeeded() {
    const { workspaceId } = this.context(); if (this.seeded.has(workspaceId)) return this.seeded.get(workspaceId);
    const promise = (async () => {
      if (this.context().auth.role === "viewer") return;
      await this.insert("settings", [{ key: "business_profile", value: DEFAULT_PROFILE }, { key: "supplier", value: DEFAULT_PROFILE }, { key: "number_prefixes", value: DEFAULT_PREFIXES }], { onConflict: "workspace_id,key", upsert: "ignore", single: false });
      await this.insert("email_templates", Object.values(DEFAULT_EMAIL_TEMPLATES).map((template) => ({ ...template, updated_at: now() })), { onConflict: "workspace_id,purpose", upsert: "ignore", single: false });
      await this.insert("reminder_rules", DEFAULT_REMINDER_RULES.map((rule) => ({ ...rule, created_at: now(), updated_at: now() })), { onConflict: "workspace_id,id", upsert: "ignore", single: false });
      if (!(await this.select("branding_presets", "limit=1")).length) await this.insert("branding_presets", { id: randomUUID(), name: "Forma default", data_json: { template_id: "classic", accent: "#7f56d9", logo_url: "", footer: "" }, created_at: now(), updated_at: now() });
    })().catch((cause) => { this.seeded.delete(workspaceId); throw cause; });
    this.seeded.set(workspaceId, promise); return promise;
  }

  async getSetting(key, fallback) { const rows = await this.select("settings", `key=eq.${encodeURIComponent(key)}&limit=1`); return rows[0]?.value ?? fallback; }
  async setting(key, value) { return this.insert("settings", { key, value }, { onConflict: "workspace_id,key", upsert: true }); }
  async getBusinessProfile() { await this.ensureSeeded(); return { ...DEFAULT_PROFILE, ...await this.getSetting("business_profile", DEFAULT_PROFILE) }; }
  async saveBusinessProfile(input = {}) { const current = await this.getBusinessProfile(); const profile = { ...DEFAULT_PROFILE, ...current, ...input, default_currency: String(input.default_currency || current.default_currency || "ZAR").toUpperCase() }; await this.setting("business_profile", profile); await this.setting("supplier", profile); return profile; }
  async prefixes() { await this.ensureSeeded(); return { ...DEFAULT_PREFIXES, ...await this.getSetting("number_prefixes", {}) }; }
  async savePrefixes(value = {}) { for (const type of TYPES) if (value[type] !== undefined && !/^[A-Z0-9]{2,10}$/i.test(value[type])) throw domainError(`Prefix for ${type} must be 2-10 letters or digits`); const merged = { ...await this.prefixes(), ...value }; await this.setting("number_prefixes", merged); return merged; }
  async defaultPaymentMethod() { const rows = await this.select("payment_methods", "active=eq.true&is_default=eq.true&limit=1", { useService: true }); return mapPaymentMethod(rows[0], true); }
  async normalizeData(input = {}, type = "invoice", number = input.number || "") {
    assertType(type); const profile = await this.getBusinessProfile(); const template = templateFor(input.template_id || "classic");
    if (input.page_size && !["A4", "LETTER"].includes(input.page_size)) throw domainError("page_size must be A4 or LETTER");
    if (input.shipping_minor !== undefined) asMinor(input.shipping_minor, "shipping_minor");
    if (input.document_discount_bps !== undefined && (Number(input.document_discount_bps) < 0 || Number(input.document_discount_bps) > 10000)) throw domainError("document_discount_bps must be between 0 and 10000");
    const items = Array.isArray(input.items) ? input.items : [];
    for (const [index, item] of items.entries()) { if (item.quantity !== undefined && (!Number.isFinite(Number(item.quantity)) || Number(item.quantity) < 0)) throw domainError(`items[${index}].quantity cannot be negative`); if (item.unit_price_minor !== undefined) asMinor(item.unit_price_minor, `items[${index}].unit_price_minor`); if (item.tax_bps !== undefined && (Number(item.tax_bps) < 0 || Number(item.tax_bps) > 10000)) throw domainError(`items[${index}].tax_bps must be between 0 and 10000`); if (item.discount_bps !== undefined && (Number(item.discount_bps) < 0 || Number(item.discount_bps) > 10000)) throw domainError(`items[${index}].discount_bps must be between 0 and 10000`); }
    const payment = await this.defaultPaymentMethod(); const termsDays = Number(input.terms_days) || profile.default_terms_days || 30;
    return { ...input, document_type: type, document_title: input.document_title || (type === "quote" ? "Quote" : type === "receipt" ? "Receipt" : "Tax Invoice"), number, issue_date: input.issue_date || today(), due_date: input.due_date || addDays(today(), termsDays), terms_days: termsDays, currency: String(input.currency || profile.default_currency || "ZAR").toUpperCase(), customer_id: input.customer_id || null, customer: input.customer || {}, supplier: input.supplier || profile, items, payment_method_id: input.payment_method_id || payment?.id || null, payment_method: input.payment_method || payment?.name || "Bank transfer", payment_details: input.payment_details || payment?.details?.instructions || "", po_number: input.po_number || "", notes: input.notes || "", shipping_minor: Math.round(Number(input.shipping_minor) || 0), document_discount_bps: Math.round(Number(input.document_discount_bps) || 0), attachments: Array.isArray(input.attachments) ? input.attachments : [], template_id: template.id, page_size: input.page_size || "A4", accent: input.accent || template.accent, brand: input.brand || {}, signature: input.signature || "", footer: input.footer || "" };
  }

  async audit(documentId, type, detail = {}) { return this.insert("document_audit_events", { document_id: documentId, type, detail_json: detail, created_at: now() }); }
  async allocateNumber(type = "invoice", year = new Date().getFullYear()) { assertType(type); const value = await this.rpc("allocate_document_number", { target_workspace: this.context().workspaceId, target_type: type, target_year: year }); return Array.isArray(value) ? value[0] : value; }
  async getDocument(id, options = {}) { const rows = await this.select("documents", `id=eq.${encodeURIComponent(id)}&limit=1`); const document = mapDocument(rows[0]); if (document && options.sensitive && document.data.payment_method_id) document.payment_method = await this.getPaymentMethod(document.data.payment_method_id, this.context().auth.role !== "viewer"); return document; }
  async listDocuments({ document_type, status } = {}) { if (document_type) assertType(document_type); let query = "order=updated_at.desc"; if (document_type) query += `&document_type=eq.${encodeURIComponent(document_type)}`; if (status) query += `&status=eq.${encodeURIComponent(status)}`; return (await this.select("documents", query)).map(mapDocument); }
  async createDocument(input = {}, options = {}) {
    const type = input.document_type || "invoice"; assertType(type); const year = new Date().getFullYear(); const requestedNumber = input.number || ""; const data = await this.normalizeData({ ...input, number: requestedNumber }, type, requestedNumber); const totals = calculateTotals(data); const row = await this.rpc("create_document_record", { target_workspace: this.context().workspaceId, target_id: options.id || randomUUID(), target_type: type, target_year: year, requested_number: requestedNumber, target_customer_id: data.customer_id || null, target_source_document_id: options.source_document_id || null, target_recurring_schedule_id: options.recurring_schedule_id || null, target_data: data, target_totals: totals }); return mapDocument(row);
  }
  async updateDocument(id, input = {}) { const existing = await this.getDocument(id); if (!existing) throw domainError("Document not found", 404, "NOT_FOUND"); if (existing.status !== "draft") throw domainError("Issued documents cannot be edited", 409, "CONFLICT"); const data = await this.normalizeData({ ...existing.data, ...input, number: input.number || existing.number }, existing.document_type, input.number || existing.number); const totals = calculateTotals(data); const row = await this.update("documents", `id=eq.${encodeURIComponent(id)}&status=eq.draft`, { number: data.number, customer_id: data.customer_id || null, data_json: data, totals_json: totals, balance_due_minor: totals.total_minor, updated_at: now() }); if (!row) throw domainError("Document changed before it could be saved", 409, "CONFLICT"); await this.audit(id, "updated"); return mapDocument(row); }
  async finalizeDocument(id, markSent = false) { const document = await this.getDocument(id); if (!document) throw domainError("Document not found", 404, "NOT_FOUND"); if (document.status !== "draft") throw domainError("Only drafts can be finalized", 409, "CONFLICT"); const data = withoutPristineTrailingItems(document.data); const totals = calculateTotals(data); const check = readiness(data, totals, document.document_type); if (!check.ready) throw domainError("Document is not ready to finalize", 422, "VALIDATION_ERROR", check.checks.filter((item) => !item.complete)); const timestamp = now(); const status = document.document_type === "receipt" ? "issued" : document.document_type === "quote" ? "sent" : markSent ? "sent" : "finalized"; const snapshot = { ...data, totals, issued_at: timestamp }; const row = await this.rpc("finalize_document_record", { target_workspace: this.context().workspaceId, target_id: id, target_status: status, target_data: data, target_totals: totals, target_snapshot: snapshot, target_balance: Math.max(0, totals.total_minor - document.amount_paid_minor), sent_event: markSent || document.document_type === "quote" }); return mapDocument(row); }
  async transitionDocument(id, status, event = status) { const document = await this.getDocument(id); if (!document) throw domainError("Document not found", 404, "NOT_FOUND"); assertStatus(document.document_type, status); const transitions = { quote: { sent: ["draft"], accepted: ["sent"], declined: ["sent"], expired: ["draft", "sent"] }, invoice: { sent: ["draft", "finalized"], overdue: ["finalized", "sent", "partially_paid"], void: ["draft", "finalized", "sent", "partially_paid", "overdue"], refunded: ["paid", "partially_paid"] }, receipt: { void: ["draft", "issued"] } }; if (!transitions[document.document_type][status]?.includes(document.status)) throw domainError(`Cannot transition ${document.document_type} from ${document.status} to ${status}`, 409, "CONFLICT"); return mapDocument(await this.rpc("transition_document_record", { target_workspace: this.context().workspaceId, target_id: id, expected_status: document.status, target_status: status, event_type: event })); }
  async duplicate(id) { const source = await this.getDocument(id); if (!source) throw domainError("Document not found", 404, "NOT_FOUND"); const base = source.snapshot || source.data; return this.createDocument({ ...base, document_type: source.document_type, number: undefined, issue_date: today(), due_date: addDays(today(), base.terms_days || 30) }); }
  async convertQuote(id) { const quote = await this.getDocument(id); if (!quote || quote.document_type !== "quote") throw domainError("Quote not found", 404, "NOT_FOUND"); if (quote.status !== "accepted") throw domainError("Only accepted quotes can be converted", 409, "CONFLICT"); const base = quote.snapshot || quote.data; const data = await this.normalizeData({ ...base, document_type: "invoice", document_title: "Tax Invoice", number: "" }, "invoice", ""); const totals = calculateTotals(data); const row = await this.rpc("convert_quote_record", { target_workspace: this.context().workspaceId, quote_id: id, invoice_id: randomUUID(), invoice_year: new Date().getFullYear(), invoice_data: data, invoice_totals: totals }); return mapDocument(row); }

  async getPayment(id) { const rows = await this.select("payments", `id=eq.${encodeURIComponent(id)}&limit=1`); return rows[0] || null; }
  async listPayments(invoiceId) { return this.select("payments", `invoice_id=eq.${encodeURIComponent(invoiceId)}&order=received_date.asc,id.asc`); }
  async recordPayment(id, input = {}) { const invoice = await this.getDocument(id); if (!invoice || invoice.document_type !== "invoice") throw domainError("Invoice not found", 404, "NOT_FOUND"); if (!["finalized", "sent", "partially_paid", "overdue"].includes(invoice.status)) throw domainError("Payments can only be recorded against an issued invoice", 409, "CONFLICT"); const amount = asMinor(input.amount_minor, "amount_minor", { allowZero: false }); if (amount > invoice.balance_due_minor) throw domainError("Payment exceeds outstanding balance"); const method = String(input.method || "Bank transfer").trim(); if (!method) throw domainError("method is required"); const createReceipt = input.create_receipt !== false; let receiptData = null; let receiptTotals = null; const receiptId = createReceipt ? randomUUID() : null;
    if (createReceipt) { receiptData = await this.normalizeData({ document_title: "Receipt", currency: invoice.data.currency, customer: invoice.data.customer, customer_id: invoice.customer_id, supplier: invoice.data.supplier, template_id: invoice.data.template_id, page_size: invoice.data.page_size, accent: invoice.data.accent, payment_method: method, payment_details: invoice.data.payment_details, receipt_for: invoice.number, items: [{ description: `Payment for ${invoice.number}`, quantity: 1, unit_price_minor: amount, tax_bps: 0, discount_bps: 0 }], notes: input.notes || "", document_type: "receipt", number: "" }, "receipt", ""); receiptTotals = calculateTotals(receiptData); }
    const result = await this.rpc("record_invoice_payment", { target_workspace: this.context().workspaceId, invoice_id: id, payment_id: randomUUID(), payment_amount: amount, payment_method: method, payment_reference: input.reference || "", payment_received_date: input.received_date || today(), payment_notes: input.notes || "", receipt_id: receiptId, receipt_year: createReceipt ? new Date().getFullYear() : null, receipt_data: receiptData, receipt_totals: receiptTotals }); return { payment: result.payment, receipt: mapDocument(result.receipt), invoice: mapDocument(result.invoice) }; }

  async getPaymentMethod(id, sensitive = false) { const rows = await this.select("payment_methods", `id=eq.${encodeURIComponent(id)}&limit=1`, { useService: true }); return mapPaymentMethod(rows[0], sensitive); }
  async listPaymentMethods() { await this.ensureSeeded(); return (await this.select("payment_methods", "order=is_default.desc,name.asc", { useService: true })).map((row) => mapPaymentMethod(row)); }
  async savePaymentMethod(input, id = input.id || randomUUID()) { if (!input.name) throw domainError("Payment method name is required"); return mapPaymentMethod(await this.rpc("save_payment_method_record", { target_workspace: this.context().workspaceId, target_id: id, target_name: input.name, target_method_type: input.method_type || "bank_transfer", target_details: input.details || {}, target_active: input.active !== false, requested_default: input.is_default === undefined ? null : Boolean(input.is_default) }), true); }
  async setDefaultPaymentMethod(id) { return mapPaymentMethod(await this.rpc("set_default_payment_method_record", { target_workspace: this.context().workspaceId, target_id: id }), true); }
  async saveMediaAsset(input, id = input.id || randomUUID()) { if (!input.storage_key || !input.filename || !input.content_type) throw domainError("Asset metadata is incomplete"); const size = asMinor(input.byte_size, "byte_size"); return this.insert("media_assets", { id, storage_key: input.storage_key, filename: input.filename, content_type: input.content_type, byte_size: size, created_at: now() }); }
  async getMediaAsset(id) { const rows = await this.select("media_assets", `id=eq.${encodeURIComponent(id)}&limit=1`); return rows[0] || null; }
  async deleteMediaAsset(id) { return this.remove("media_assets", `id=eq.${encodeURIComponent(id)}`); }
  async listBrandingPresets() { await this.ensureSeeded(); return (await this.select("branding_presets", "order=name.asc")).map((row) => ({ id: row.id, name: row.name, ...(row.data_json || {}), created_at: row.created_at, updated_at: row.updated_at })); }
  async saveBrandingPreset(input, id = input.id || randomUUID()) { if (!input.name) throw domainError("Branding preset name is required"); if (input.template_id) templateFor(input.template_id); const row = await this.insert("branding_presets", { id, name: input.name, data_json: { template_id: input.template_id || "classic", accent: input.accent || "#7f56d9", logo_url: input.logo_url || "", footer: input.footer || "" }, created_at: now(), updated_at: now() }, { onConflict: "id", upsert: true }); return { id: row.id, name: row.name, ...row.data_json, created_at: row.created_at, updated_at: row.updated_at }; }

  async listEmailTemplates() { await this.ensureSeeded(); return (await this.select("email_templates", "order=purpose.asc")).map(({ workspace_id, ...row }) => row); }
  async getEmailTemplate(purpose) { const rows = await this.select("email_templates", `purpose=eq.${encodeURIComponent(purpose)}&limit=1`); if (!rows[0]) throw domainError("Email template not found", 404, "NOT_FOUND"); const { workspace_id, ...template } = rows[0]; return template; }
  async saveEmailTemplate(input) { if (!PURPOSES.includes(input.purpose)) throw domainError(`purpose must be one of: ${PURPOSES.join(", ")}`); validateTemplate(input); const row = await this.insert("email_templates", { purpose: input.purpose, subject: input.subject || "", text: input.text || "", html: input.html || "", updated_at: now() }, { onConflict: "workspace_id,purpose", upsert: true }); const { workspace_id, ...template } = row; return template; }
  async restoreEmailTemplate(purpose) { const template = DEFAULT_EMAIL_TEMPLATES[purpose]; if (!template) throw domainError(`Unknown email template purpose '${purpose}'`); return this.saveEmailTemplate(template); }
  async emailVariables(document, message = "") { const data = document.snapshot || document.data; const money = (minor) => new Intl.NumberFormat("en-ZA", { style: "currency", currency: data.currency || "ZAR" }).format((minor || 0) / 100); const businessName = data.supplier?.name || (await this.getBusinessProfile()).name; return { document_number: document.number, document_type: document.document_type, customer_name: data.customer?.name || "Customer", business_name: businessName, sender_name: businessName, currency: data.currency || "ZAR", subtotal: money(document.totals.subtotal_minor), total: money(document.totals.total_minor), amount_paid: money(document.amount_paid_minor), balance_due: money(document.balance_due_minor), due_date: data.due_date || "", expiry_date: data.expiry_date || data.due_date || "", issue_date: data.issue_date || "", payment_method: data.payment_method || "", payment_link: data.payment_link || "", document_link: data.document_link || "", message }; }
  async createEmailDraft(documentId, { purpose, message = "", subject, body } = {}) { const document = await this.getDocument(documentId); if (!document) throw domainError("Document not found", 404, "NOT_FOUND"); const selected = purpose || `${document.document_type}_send`; const template = await this.getEmailTemplate(PURPOSES.includes(selected) ? selected : "document_generic"); const rendered = renderTemplate(template, await this.emailVariables(document, message)); const customBody = typeof body === "string" && body.trim() ? body.trim() : null; const customSubject = typeof subject === "string" && subject.trim() ? subject.trim() : null; if (customSubject && customSubject.length > 240) throw domainError("Email subject must be 240 characters or fewer"); return { document_id: documentId, purpose: template.purpose, recipients: document.data.customer?.email ? [document.data.customer.email] : [], subject: customSubject || rendered.subject, text: customBody || rendered.text, html: customBody ? safeHtml(customBody).replace(/\r?\n/g, "<br>") : rendered.html }; }
  async beginDocumentEmail(id, input = {}, provider = "mock") { const requestKey = String(input.request_key || input.idempotency_key || "").trim(); if (!requestKey || requestKey.length > 256) throw domainError("request_key is required and must be 256 characters or fewer"); const document = await this.getDocument(id, { sensitive: true }); if (!document) throw domainError("Document not found", 404, "NOT_FOUND"); if (document.status === "draft" && !readiness(document.data, document.totals, document.document_type).ready) throw domainError("Document must be complete before it can be sent", 422, "VALIDATION_ERROR"); const draft = await this.createEmailDraft(id, input); const to = Array.isArray(input.to) ? input.to : input.to ? [input.to] : Array.isArray(input.recipients) ? input.recipients : draft.recipients; const cc = Array.isArray(input.cc) ? input.cc : input.cc ? [input.cc] : []; const bcc = Array.isArray(input.bcc) ? input.bcc : input.bcc ? [input.bcc] : []; const recipients = [...new Set([...to, ...cc, ...bcc].map((address) => String(address).trim()).filter(Boolean))]; if (!to.length || recipients.some((address) => !validAddress(address))) throw domainError("Enter at least one valid recipient email address"); const rendered = { subject: draft.subject, text: draft.text, html: draft.html, to, cc, bcc }; const result = await this.rpc("begin_email_delivery_record", { target_workspace: this.context().workspaceId, target_id: randomUUID(), target_document_id: id, target_request_key: requestKey, target_recipients: recipients, target_template_purpose: draft.purpose, target_provider: provider, target_rendered: rendered }); return { attempt: mapEmailAttempt(result.attempt, !result.inserted), document, idempotent: !result.inserted }; }
  async completeDocumentEmail(id, attemptId, delivery = {}) { const document = await this.getDocument(id); if (!document) throw domainError("Document not found", 404, "NOT_FOUND"); let data = null; let totals = null; let snapshot = null; let balance = null; let status = null; if (delivery.accepted && document.status === "draft") { data = withoutPristineTrailingItems(document.data); totals = calculateTotals(data); const check = readiness(data, totals, document.document_type); if (!check.ready) throw domainError("Document is not ready to finalize", 422, "VALIDATION_ERROR", check.checks.filter((item) => !item.complete)); const timestamp = now(); snapshot = { ...data, totals, issued_at: timestamp }; balance = Math.max(0, totals.total_minor - document.amount_paid_minor); status = document.document_type === "receipt" ? "issued" : "sent"; } const row = await this.rpc("complete_email_delivery_record", { target_workspace: this.context().workspaceId, target_document_id: id, target_attempt_id: attemptId, delivery_accepted: Boolean(delivery.accepted), delivery_status: delivery.status || (delivery.accepted ? "accepted" : "failed"), delivery_message_id: delivery.message_id || null, delivery_error: delivery.accepted ? null : String(delivery.error || "Delivery was not accepted"), finalize_status: status, finalize_data: data, finalize_totals: totals, finalize_snapshot: snapshot, finalize_balance: balance }); return mapEmailAttempt(row); }
  async listEmailHistory(id) { return (await this.select("email_delivery_attempts", `document_id=eq.${id}&order=created_at.desc`)).map((row) => mapEmailAttempt(row)); }
  async listAudit(id) { return (await this.select("document_audit_events", `document_id=eq.${id}&order=id.asc`)).map((row) => ({ id: row.id, type: row.type, detail: row.detail_json || {}, created_at: row.created_at })); }

  async listCustomers(query = "") { let suffix = "order=updated_at.desc"; if (query) suffix += `&or=(name.ilike.*${encodeURIComponent(query)}*,email.ilike.*${encodeURIComponent(query)}*)`; return (await this.select("customers", suffix)).map(({ workspace_id, ...row }) => row); }
  async getCustomer(id) { const rows = await this.select("customers", `id=eq.${encodeURIComponent(id)}&limit=1`); if (!rows[0]) return null; const { workspace_id, ...row } = rows[0]; return row; }
  async saveCustomer(input, id = randomUUID()) { if (!input.name) throw domainError("Customer name is required"); const existing = await this.getCustomer(id); const row = await this.insert("customers", { id, name: input.name, contact_name: input.contact_name || "", email: input.email || "", phone: input.phone || "", address: input.address || "", country: input.country || "South Africa", vat_number: input.vat_number || "", registration_number: input.registration_number || "", notes: input.notes || "", vat_registered: Boolean(input.vat_registered), currency: input.currency || "ZAR", terms_days: Number(input.terms_days) || 30, created_at: existing?.created_at || now(), updated_at: now() }, { onConflict: "id", upsert: true }); const { workspace_id, ...customer } = row; return customer; }
  async listProducts(query = "") { let suffix = "order=updated_at.desc"; if (query) suffix += `&or=(name.ilike.*${encodeURIComponent(query)}*,description.ilike.*${encodeURIComponent(query)}*)`; return (await this.select("products", suffix)).map(({ workspace_id, ...row }) => row); }
  async saveProduct(input, id = randomUUID()) { if (!input.name) throw domainError("Product name is required"); asMinor(input.unit_price_minor || 0, "unit_price_minor"); const row = await this.insert("products", { id, name: input.name, description: input.description || "", unit_price_minor: Math.round(Number(input.unit_price_minor) || 0), tax_bps: Math.round(Number(input.tax_bps) || 0), currency: input.currency || "ZAR", created_at: now(), updated_at: now() }, { onConflict: "id", upsert: true }); const { workspace_id, ...product } = row; return product; }

  async listReminderRules() { await this.ensureSeeded(); return (await this.select("reminder_rules", "order=offset_days.asc,id.asc")).map(mapReminderRule); }
  async getReminderRule(id) { const rows = await this.select("reminder_rules", `id=eq.${encodeURIComponent(id)}&limit=1`); return mapReminderRule(rows[0]); }
  async saveReminderRule(input = {}, id = input.id || randomUUID()) { const existing = await this.getReminderRule(id); if (input.id && !existing) throw domainError("Reminder rule not found", 404, "NOT_FOUND"); const offset = Math.round(Number(input.offset_days ?? existing?.offset_days ?? 0)); const label = String(input.label ?? existing?.label ?? "").trim(); const purpose = String(input.purpose ?? existing?.purpose ?? (offset > 0 ? "invoice_overdue" : "invoice_reminder")); if (!label || label.length > 80) throw domainError("Reminder label must be between 1 and 80 characters"); if (offset < -90 || offset > 365) throw domainError("Reminder offset must be between 90 days before and 365 days after due date"); if (!PURPOSES.includes(purpose)) throw domainError("Reminder purpose is invalid"); return mapReminderRule(await this.insert("reminder_rules", { id, label, offset_days: offset, purpose, active: input.active === undefined ? existing?.active ?? true : Boolean(input.active), created_at: existing?.created_at || now(), updated_at: now() }, { onConflict: "workspace_id,id", upsert: true })); }
  async setReminderRuleActive(id, active) { if (!await this.getReminderRule(id)) throw domainError("Reminder rule not found", 404, "NOT_FOUND"); return mapReminderRule(await this.update("reminder_rules", `id=eq.${id}`, { active: Boolean(active), updated_at: now() })); }
  async listReminderDeliveries(documentId) { const filter = documentId ? `document_id=eq.${documentId}&` : ""; return (await this.select("document_reminder_deliveries", `${filter}order=created_at.desc`)).map(mapReminderDelivery); }
  async listDueInvoiceReminders({ as_of = today(), limit = 50 } = {}) { const asOf = dateOnly(as_of, "as_of"); const rules = (await this.listReminderRules()).filter((rule) => rule.active); const documents = (await this.listDocuments({ document_type: "invoice" })).filter((document) => ["sent", "partially_paid", "overdue"].includes(document.status) && document.balance_due_minor > 0); const deliveries = await this.listReminderDeliveries(); const candidates = []; for (const document of documents) { const data = document.snapshot || document.data; if (!data.due_date) continue; const dueDate = dateOnly(data.due_date, "due_date"); const due = rules.map((rule) => ({ rule, scheduled_for: addDays(dueDate, rule.offset_days) })).filter((entry) => entry.scheduled_for <= asOf && !deliveries.some((delivery) => delivery.document_id === document.id && delivery.rule_id === entry.rule.id && delivery.due_date === dueDate)).sort((a, b) => b.scheduled_for.localeCompare(a.scheduled_for)); if (!due.length) continue; const [selected, ...skipped] = due; candidates.push({ document, rule: selected.rule, due_date: dueDate, scheduled_for: selected.scheduled_for, days_overdue: Math.max(0, Math.round((new Date(`${asOf}T12:00:00Z`) - new Date(`${dueDate}T12:00:00Z`)) / 86400000)), balance_due_minor: document.balance_due_minor, currency: data.currency || "ZAR", customer: data.customer || {}, skipped_rules: skipped.map((entry) => ({ rule: entry.rule, scheduled_for: entry.scheduled_for })) }); if (candidates.length >= limit) break; } return candidates; }
  async claimInvoiceReminder(input = {}) { const document = await this.getDocument(input.document_id || input.document?.id); const rule = await this.getReminderRule(input.rule_id || input.rule?.id); if (!document || document.document_type !== "invoice") throw domainError("Invoice not found", 404, "NOT_FOUND"); if (!rule) throw domainError("Reminder rule not found", 404, "NOT_FOUND"); const dueDate = dateOnly(input.due_date, "due_date"); const scheduledFor = input.scheduled_for || addDays(dueDate, rule.offset_days); const skipped = (input.skipped_rules || []).map((entry) => { const skippedRule = entry.rule || entry; return { id: randomUUID(), rule_id: skippedRule.id, scheduled_for: entry.scheduled_for || addDays(dueDate, skippedRule.offset_days) }; }); const result = await this.rpc("claim_reminder_delivery_record", { target_workspace: this.context().workspaceId, target_id: randomUUID(), target_document_id: document.id, target_rule_id: rule.id, target_due_date: dueDate, target_scheduled_for: scheduledFor, skipped_deliveries: skipped }); return { claimed: result.claimed, delivery: mapReminderDelivery(result.delivery) }; }
  async completeInvoiceReminderDelivery(id, attempt = {}) { const status = attempt.provider_status || attempt.status || "failed"; return mapReminderDelivery(await this.rpc("complete_reminder_delivery_record", { target_workspace: this.context().workspaceId, target_delivery_id: id, target_attempt_id: attempt.id || null, target_status: status, target_error: attempt.provider_error || attempt.error || null })); }

  async recurringRuns(scheduleId) { const runs = await this.select("recurring_schedule_runs", `schedule_id=eq.${scheduleId}&order=run_date.desc`); const result = []; for (const run of runs) { const document = await this.getDocument(run.document_id); result.push({ id: run.id, run_date: run.run_date, created_at: run.created_at, document_id: run.document_id, number: document?.number, status: document?.status, totals: document?.totals || {} }); } return result; }
  async mapRecurring(row) { return row && { id: row.id, source_document_id: row.source_document_id || null, name: row.name, frequency: row.frequency, next_run_on: row.next_run_on, ends_on: row.ends_on || null, active: Boolean(row.active), data: row.data_json || {}, last_run_on: row.last_run_on || null, generated_count: row.generated_count, created_at: row.created_at, updated_at: row.updated_at, runs: await this.recurringRuns(row.id) }; }
  async getRecurringSchedule(id) { const rows = await this.select("recurring_schedules", `id=eq.${id}&limit=1`); return this.mapRecurring(rows[0]); }
  async listRecurringSchedules() { const rows = await this.select("recurring_schedules", "order=active.desc,next_run_on.asc,name.asc"); return Promise.all(rows.map((row) => this.mapRecurring(row))); }
  async saveRecurringSchedule(input = {}, id = input.id || randomUUID()) { const existing = await this.getRecurringSchedule(id); if (input.id && !existing) throw domainError("Recurring schedule not found", 404, "NOT_FOUND"); const sourceId = input.source_document_id === undefined ? existing?.source_document_id || null : input.source_document_id || null; const source = sourceId ? await this.getDocument(sourceId, { sensitive: true }) : null; if (sourceId && !source) throw domainError("Source invoice not found", 404, "NOT_FOUND"); if (!source && !input.data && !existing?.data) throw domainError("A source invoice or recurring invoice data is required"); const nextRunOn = dateOnly(input.next_run_on ?? existing?.next_run_on ?? today(), "next_run_on"); const endsOn = input.ends_on === undefined ? existing?.ends_on || null : input.ends_on || null; if (endsOn && dateOnly(endsOn, "ends_on") < nextRunOn) throw domainError("ends_on cannot be before next_run_on"); const frequency = input.frequency ?? existing?.frequency ?? "monthly"; nextRecurringDate(nextRunOn, frequency); const sourceData = source ? source.snapshot || source.data : {}; const dataInput = input.data ?? existing?.data ?? sourceData; const terms = Math.max(0, Number(dataInput.terms_days) || (await this.getBusinessProfile()).default_terms_days || 30); const data = await this.normalizeData({ ...dataInput, document_type: "invoice", number: "", issue_date: nextRunOn, due_date: addDays(nextRunOn, terms), terms_days: terms }, "invoice", ""); const name = String(input.name ?? existing?.name ?? `${data.customer?.name || "Client"} recurring invoice`).trim(); if (!name || name.length > 120) throw domainError("Schedule name must be between 1 and 120 characters"); const row = await this.insert("recurring_schedules", { id, source_document_id: sourceId, name, frequency, next_run_on: nextRunOn, ends_on: endsOn || null, active: input.active === undefined ? existing?.active ?? true : Boolean(input.active), data_json: data, last_run_on: existing?.last_run_on || null, generated_count: existing?.generated_count || 0, created_at: existing?.created_at || now(), updated_at: now() }, { onConflict: "id", upsert: true }); return this.mapRecurring(row); }
  async setRecurringScheduleActive(id, active) { if (!await this.getRecurringSchedule(id)) throw domainError("Recurring schedule not found", 404, "NOT_FOUND"); return this.mapRecurring(await this.update("recurring_schedules", `id=eq.${id}`, { active: Boolean(active), updated_at: now() })); }
  async runDueRecurringSchedules({ as_of = today(), schedule_id } = {}) { const until = dateOnly(as_of, "as_of"); const schedules = schedule_id ? [await this.getRecurringSchedule(schedule_id)] : await this.listRecurringSchedules(); if (schedule_id && !schedules[0]) throw domainError("Recurring schedule not found", 404, "NOT_FOUND"); const generated = []; for (let schedule of schedules.filter(Boolean)) { while (schedule.active && schedule.next_run_on <= until && (!schedule.ends_on || schedule.next_run_on <= schedule.ends_on)) { const runDate = schedule.next_run_on; const data = await this.normalizeData({ ...schedule.data, document_type: "invoice", number: "", issue_date: runDate, due_date: addDays(runDate, schedule.data.terms_days || 30) }, "invoice", ""); const totals = calculateTotals(data); const result = await this.rpc("create_recurring_run_record", { target_workspace: this.context().workspaceId, target_schedule_id: schedule.id, target_run_date: runDate, target_document_id: randomUUID(), target_document_year: new Date(`${runDate}T12:00:00Z`).getUTCFullYear(), target_data: data, target_totals: totals, target_next_run_on: nextRecurringDate(runDate, schedule.frequency) }); if (result.created) generated.push(mapDocument(result.document)); schedule = await this.getRecurringSchedule(schedule.id); } if (schedule.active && schedule.ends_on && schedule.next_run_on > schedule.ends_on) await this.update("recurring_schedules", `id=eq.${schedule.id}`, { active: false, updated_at: now() }); } return { documents: generated, schedules: schedule_id ? [await this.getRecurringSchedule(schedule_id)] : await this.listRecurringSchedules() }; }

  async createDraft(input = {}) { return this.createDocument({ ...input, document_type: "invoice" }); }
  async updateDraft(id, input) { const document = await this.getDocument(id); if (document?.document_type !== "invoice") throw domainError("Invoice not found", 404, "NOT_FOUND"); return this.updateDocument(id, input); }
  async finalize(id, markSent = false) { const document = await this.getDocument(id); if (document?.document_type !== "invoice") throw domainError("Invoice not found", 404, "NOT_FOUND"); return this.finalizeDocument(id, markSent); }
  async transition(id, status, allowed, event) { const document = await this.getDocument(id); if (!document || document.document_type !== "invoice") throw domainError("Invoice not found", 404, "NOT_FOUND"); if (!allowed.includes(document.status)) throw domainError(`Cannot mark ${document.status} invoice as ${status}`, 409, "CONFLICT"); return mapDocument(await this.rpc("transition_document_record", { target_workspace: this.context().workspaceId, target_id: id, expected_status: document.status, target_status: status, event_type: event })); }
  async getInvoice(id) { const document = await this.getDocument(id, { sensitive: true }); return document?.document_type === "invoice" ? document : null; }
  async listInvoices() { return this.listDocuments({ document_type: "invoice" }); }
}

export function createSupabaseStore(options) { return new SupabaseStore(options); }
